//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIPIT09.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shippings
    {
        public int shipping_id { get; set; }
        public int client_id { get; set; }
        public int service_id { get; set; }
        public System.DateTime shipping_date { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Services Services { get; set; }
    }
}
