//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIPIT_10
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Services
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Services()
        {
            this.Shippings = new HashSet<Shippings>();
        }

        public int service_id { get; set; }
        [Required]
        [Display(Name = "Название услуги")]
        public string service_title { get; set; }
        [Required]
        [Display(Name = "Стоимость услуги")]
        [Range(1, int.MaxValue, ErrorMessage = "Значение должно быть больше или равно 1")]
        public int service_cost { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Shippings> Shippings { get; set; }
    }
}
