//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIPIT_10
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Shippings
    {
        public int shipping_id { get; set; }
        [Required]
        [Display(Name = "Клиент")]
        public int client_id { get; set; }
        [Required]
        [Display(Name = "Услуга")]
        public int service_id { get; set; }
        [Required]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public System.DateTime shipping_date { get; set; }

        public virtual Clients Clients { get; set; }
        public virtual Services Services { get; set; }
    }
}
