//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIPIT11
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_3
    {
        public int shipping_id { get; set; }
        public int client_id { get; set; }
        public string client_fullname { get; set; }
        public int service_id { get; set; }
        public string service_title { get; set; }
        public int service_cost { get; set; }
        public System.DateTime shipping_date { get; set; }
    }
}
